[package]
name = "rust-grpc-example"
version = "0.1.0"
authors = ["swiftdiaries <adhita94@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tonic = {workspace = true}
prost = "0.13"
prost-types = "0.13"
tokio = {workspace = true}
tifs = { path = ".." }
clap = { version = "4.4", features = ["wrap_help", "cargo"] }
clap_complete = "4.4"
clap_mangen = "0.2"
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bytes = "1.0"
bytestring = "1.0"
fuser = {git = "https://github.com/cberner/fuser.git", features = ["serializable", "abi-7-31"]}
uuid = "1.8.0"
num-bigint = "0.4.5"
num-traits = "0.2.19"
futures = "0.3.30"

[build-dependencies]
tonic-build = {workspace = true}
